const { Pool } = require('pg');
require('dotenv').config();

const pool = new Pool({
    user: process.env.DB_USER,
    host: process.env.DB_HOST,
    database: process.env.DB_NAME,
    password: process.env.DB_PASSWORD,
    port: process.env.DB_PORT,
});


const SILUETAS = [
    { nombre: 'Afghanistan', codigo: 'af' },
    { nombre: 'Albania', codigo: 'al' },
    { nombre: 'Algeria', codigo: 'dz' },
    { nombre: 'Andorra', codigo: 'ad' },
    { nombre: 'Angola', codigo: 'ao' },
    { nombre: 'Anguilla', codigo: 'ai' },
    { nombre: 'Antigua and Barbuda', codigo: 'ag' },
    { nombre: 'Argentina', codigo: 'ar' },
    { nombre: 'Armenia', codigo: 'am' },
    { nombre: 'Australia', codigo: 'au' },
    { nombre: 'Austria', codigo: 'at' },
    { nombre: 'Azerbaijan', codigo: 'az' },
    { nombre: 'Bahamas', codigo: 'bs' },
    { nombre: 'Bahrain', codigo: 'bh' },
    { nombre: 'Bangladesh', codigo: 'bd' },
    { nombre: 'Barbados', codigo: 'bb' },
    { nombre: 'Belarus', codigo: 'by' },
    { nombre: 'Belgium', codigo: 'be' },
    { nombre: 'Belize', codigo: 'bz' },
    { nombre: 'Benin', codigo: 'bj' },
    { nombre: 'Bermuda', codigo: 'bm' },
    { nombre: 'Bhutan', codigo: 'bt' },
    { nombre: 'Bolivia', codigo: 'bo' },
    { nombre: 'Bosnia and Herzegovina', codigo: 'ba' },
    { nombre: 'Botswana', codigo: 'bw' },
    { nombre: 'Brazil', codigo: 'br' },
    { nombre: 'Brunei', codigo: 'bn' },
    { nombre: 'Bulgaria', codigo: 'bg' },
    { nombre: 'Burkina Faso', codigo: 'bf' },
    { nombre: 'Burundi', codigo: 'bi' },
    { nombre: 'Cambodia', codigo: 'kh' },
    { nombre: 'Cameroon', codigo: 'cm' },
    { nombre: 'Canada', codigo: 'ca' },
    { nombre: 'Cape Verde', codigo: 'cv' },
    { nombre: 'Central African Republic', codigo: 'cf' },
    { nombre: 'Chad', codigo: 'td' },
    { nombre: 'Chile', codigo: 'cl' },
    { nombre: 'China', codigo: 'cn' },
    { nombre: 'Colombia', codigo: 'co' },
    { nombre: 'Comoros', codigo: 'km' },
    { nombre: 'Cook Islands', codigo: 'ck' },
    { nombre: 'Costa Rica', codigo: 'cr' },
    { nombre: 'Croatia', codigo: 'hr' },
    { nombre: 'Cuba', codigo: 'cu' },
    { nombre: 'Cyprus', codigo: 'cy' },
    { nombre: 'Czechia', codigo: 'cz' },
    { nombre: 'DR Congo', codigo: 'cd' },
    { nombre: 'Denmark', codigo: 'dk' },
    { nombre: 'Djibouti', codigo: 'dj' },
    { nombre: 'Dominica', codigo: 'dm' },
    { nombre: 'Dominican Republic', codigo: 'do' },
    { nombre: 'Ecuador', codigo: 'ec' },
    { nombre: 'Egypt', codigo: 'eg' },
    { nombre: 'El Salvador', codigo: 'sv' },
    { nombre: 'Equatorial Guinea', codigo: 'gq' },
    { nombre: 'Eritrea', codigo: 'er' },
    { nombre: 'Estonia', codigo: 'ee' },
    { nombre: 'Eswatini', codigo: 'sz' },
    { nombre: 'Ethiopia', codigo: 'et' },
    { nombre: 'Fiji', codigo: 'fj' },
    { nombre: 'Finland', codigo: 'fi' },
    { nombre: 'France', codigo: 'fr' },
    { nombre: 'Gabon', codigo: 'ga' },
    { nombre: 'Gambia', codigo: 'gm' },
    { nombre: 'Georgia', codigo: 'ge' },
    { nombre: 'Germany', codigo: 'de' },
    { nombre: 'Ghana', codigo: 'gh' },
    { nombre: 'Greece', codigo: 'gr' },
    { nombre: 'Greenland', codigo: 'gl' },
    { nombre: 'Grenada', codigo: 'gd' },
    { nombre: 'Guadeloupe', codigo: 'gp' },
    { nombre: 'Guatemala', codigo: 'gt' },
    { nombre: 'Guinea', codigo: 'gn' },
    { nombre: 'Guinea-Bissau', codigo: 'gw' },
    { nombre: 'Guyana', codigo: 'gy' },
    { nombre: 'Haiti', codigo: 'ht' },
    { nombre: 'Honduras', codigo: 'hn' },
    { nombre: 'Hungary', codigo: 'hu' },
    { nombre: 'Iceland', codigo: 'is' },
    { nombre: 'India', codigo: 'in' },
    { nombre: 'Indonesia', codigo: 'id' },
    { nombre: 'Iran', codigo: 'ir' },
    { nombre: 'Iraq', codigo: 'iq' },
    { nombre: 'Ireland', codigo: 'ie' },
    { nombre: 'Israel', codigo: 'il' },
    { nombre: 'Italy', codigo: 'it' },
    { nombre: 'Ivory Coast', codigo: 'ci' },
    { nombre: 'Jamaica', codigo: 'jm' },
    { nombre: 'Japan', codigo: 'jp' },
    { nombre: 'Jordan', codigo: 'jo' },
    { nombre: 'Kazakhstan', codigo: 'kz' },
    { nombre: 'Kenya', codigo: 'ke' },
    { nombre: 'Kiribati', codigo: 'ki' },
    { nombre: 'Kuwait', codigo: 'kw' },
    { nombre: 'Kyrgyzstan', codigo: 'kg' },
    { nombre: 'Laos', codigo: 'la' },
    { nombre: 'Latvia', codigo: 'lv' },
    { nombre: 'Lebanon', codigo: 'lb' },
    { nombre: 'Lesotho', codigo: 'ls' },
    { nombre: 'Liberia', codigo: 'lr' },
    { nombre: 'Libya', codigo: 'ly' },
    { nombre: 'Liechtenstein', codigo: 'li' },
    { nombre: 'Lithuania', codigo: 'lt' },
    { nombre: 'Luxembourg', codigo: 'lu' },
    { nombre: 'Madagascar', codigo: 'mg' },
    { nombre: 'Malawi', codigo: 'mw' },
    { nombre: 'Malaysia', codigo: 'my' },
    { nombre: 'Maldives', codigo: 'mv' },
    { nombre: 'Mali', codigo: 'ml' },
    { nombre: 'Malta', codigo: 'mt' },
    { nombre: 'Marshall Islands', codigo: 'mh' },
    { nombre: 'Mauritania', codigo: 'mr' },
    { nombre: 'Mauritius', codigo: 'mu' },
    { nombre: 'Mexico', codigo: 'mx' },
    { nombre: 'Micronesia', codigo: 'fm' },
    { nombre: 'Moldova', codigo: 'md' },
    { nombre: 'Monaco', codigo: 'mc' },
    { nombre: 'Mongolia', codigo: 'mn' },
    { nombre: 'Montenegro', codigo: 'me' },
    { nombre: 'Morocco', codigo: 'ma' },
    { nombre: 'Mozambique', codigo: 'mz' },
    { nombre: 'Myanmar', codigo: 'mm' },
    { nombre: 'Namibia', codigo: 'na' },
    { nombre: 'Nauru', codigo: 'nr' },
    { nombre: 'Nepal', codigo: 'np' },
    { nombre: 'Netherlands', codigo: 'nl' },
    { nombre: 'New Zealand', codigo: 'nz' },
    { nombre: 'Nicaragua', codigo: 'ni' },
    { nombre: 'Niger', codigo: 'ne' },
    { nombre: 'Nigeria', codigo: 'ng' },
    { nombre: 'North Korea', codigo: 'kp' },
    { nombre: 'North Macedonia', codigo: 'mk' },
    { nombre: 'Norway', codigo: 'no' },
    { nombre: 'Oman', codigo: 'om' },
    { nombre: 'Pakistan', codigo: 'pk' },
    { nombre: 'Palau', codigo: 'pw' },
    { nombre: 'Palestine', codigo: 'ps' },
    { nombre: 'Panama', codigo: 'pa' },
    { nombre: 'Papua New Guinea', codigo: 'pg' },
    { nombre: 'Paraguay', codigo: 'py' },
    { nombre: 'Peru', codigo: 'pe' },
    { nombre: 'Philippines', codigo: 'ph' },
    { nombre: 'Poland', codigo: 'pl' },
    { nombre: 'Portugal', codigo: 'pt' },
    { nombre: 'Puerto Rico', codigo: 'pr' },
    { nombre: 'Qatar', codigo: 'qa' },
    { nombre: 'Republic of the Congo', codigo: 'cg' },
    { nombre: 'Romania', codigo: 'ro' },
    { nombre: 'Russia', codigo: 'ru' },
    { nombre: 'Rwanda', codigo: 'rw' },
    { nombre: 'Saint Kitts and Nevis', codigo: 'kn' },
    { nombre: 'Saint Lucia', codigo: 'lc' },
    { nombre: 'Saint Vincent and the Grenadines', codigo: 'vc' },
    { nombre: 'Samoa', codigo: 'ws' },
    { nombre: 'San Marino', codigo: 'sm' },
    { nombre: 'Saudi Arabia', codigo: 'sa' },
    { nombre: 'Senegal', codigo: 'sn' },
    { nombre: 'Serbia', codigo: 'rs' },
    { nombre: 'Seychelles', codigo: 'sc' },
    { nombre: 'Sierra Leone', codigo: 'sl' },
    { nombre: 'Singapore', codigo: 'sg' },
    { nombre: 'Slovakia', codigo: 'sk' },
    { nombre: 'Slovenia', codigo: 'si' },
    { nombre: 'Solomon Islands', codigo: 'sb' },
    { nombre: 'Somalia', codigo: 'so' },
    { nombre: 'South Africa', codigo: 'za' },
    { nombre: 'South Georgia', codigo: 'gs' },
    { nombre: 'South Korea', codigo: 'kr' },
    { nombre: 'South Sudan', codigo: 'ss' },
    { nombre: 'Spain', codigo: 'es' },
    { nombre: 'Sri Lanka', codigo: 'lk' },
    { nombre: 'Sudan', codigo: 'sd' },
    { nombre: 'Suriname', codigo: 'sr' },
    { nombre: 'Sweden', codigo: 'se' },
    { nombre: 'Switzerland', codigo: 'ch' },
    { nombre: 'Syria', codigo: 'sy' },
    { nombre: 'São Tomé and Príncipe', codigo: 'st' },
    { nombre: 'Taiwan', codigo: 'tw' },
    { nombre: 'Tajikistan', codigo: 'tj' },
    { nombre: 'Tanzania', codigo: 'tz' },
    { nombre: 'Thailand', codigo: 'th' },
    { nombre: 'Timor-Leste', codigo: 'tl' },
    { nombre: 'Togo', codigo: 'tg' },
    { nombre: 'Tonga', codigo: 'to' },
    { nombre: 'Trinidad and Tobago', codigo: 'tt' },
    { nombre: 'Tunisia', codigo: 'tn' },
    { nombre: 'Turkey', codigo: 'tr' },
    { nombre: 'Turkmenistan', codigo: 'tm' },
    { nombre: 'Tuvalu', codigo: 'tv' },
    { nombre: 'Uganda', codigo: 'ug' },
    { nombre: 'Ukraine', codigo: 'ua' },
    { nombre: 'United Arab Emirates', codigo: 'ae' },
    { nombre: 'United Kingdom', codigo: 'gb' },
    { nombre: 'United States', codigo: 'us' },
    { nombre: 'Uruguay', codigo: 'uy' },
    { nombre: 'Uzbekistan', codigo: 'uz' },
    { nombre: 'Vanuatu', codigo: 'vu' },
    { nombre: 'Vatican City', codigo: 'va' },
    { nombre: 'Venezuela', codigo: 've' },
    { nombre: 'Vietnam', codigo: 'vn' },
    { nombre: 'Yemen', codigo: 'ye' },
    { nombre: 'Zambia', codigo: 'zm' },
    { nombre: 'Zimbabwe', codigo: 'zw' },
];

async function seedSiluetas() {
    try {
        console.log('🗺️  Actualizando siluetas...');

        for (const pais of SILUETAS) {
            const url = `https://raw.githubusercontent.com/djaiss/mapsicon/master/all/${pais.codigo}/256.png`;

            await pool.query(
                `UPDATE paises SET imagen_silueta = $1 WHERE nombre = $2`,
                [url, pais.nombre]
            );
        }

        console.log(`✅ ${SILUETAS.length} siluetas actualizadas`);
    } catch (error) {
        console.error('❌ Error al actualizar siluetas:', error);
    } finally {
        await pool.end();
    }
}

seedSiluetas();